version: "3.1"
services:
  postgres:
    image: "postgres:15-alpine"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=db_lucas
    ports:
      - "5432:5432"

  webserver:
    image: "nginx:alpine"
    volumes:
      - ".:/application"
      - "./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "49000:80"

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=db_lucas
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ".:/application"
      - "./phpdocker/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini"
